In [14]:
# https://www.geeksforgeeks.org/submatrix-sum-queries/
# https://en.wikipedia.org/wiki/Summed-area_table

import numpy as np

A = np.random.randint(0, 10, (3, 4))

print (A)
print (A.cumsum(axis=0).cumsum(axis=1))

[[9 9 8 0]
 [6 6 6 5]
 [5 9 9 0]]
[[ 9 18 26 26]
 [15 30 44 49]
 [20 44 67 72]]


In [15]:
A.shape

(3, 4)

In [17]:
#r = A.copy()
#copy first row

#col wise
for i in range(1,len(A)):
    for j in range(0,len(A[0])):
        r[i][j] = A[i][j]+A[i-1][j]
#row wise
for i in range(0,len(A)):
    for j in range(1,len(A[0])):
        r[i][j] += r[i][j-1]
r,A

(array([[ 9, 18, 26, 26],
        [15, 30, 44, 49],
        [11, 26, 41, 46]]), array([[9, 9, 8, 0],
        [6, 6, 6, 5],
        [5, 9, 9, 0]]))

In [12]:
len(A[0]),len(A)

(4, 3)