In [43]:
import numpy as np
from scipy.sparse import csr_matrix
A = csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])
v = np.array([1, 0, -1])
A.dot(v)

array([ 1, -3, -1], dtype=int64)

In [44]:
A.toarray(), A.data, A.todense(), A.shape, A

(array([[1, 2, 0],
        [0, 0, 3],
        [4, 0, 5]], dtype=int64),
 array([1, 2, 3, 4, 5], dtype=int64),
 matrix([[1, 2, 0],
         [0, 0, 3],
         [4, 0, 5]], dtype=int64),
 (3, 3),
 <3x3 sparse matrix of type '<class 'numpy.int64'>'
 	with 5 stored elements in Compressed Sparse Row format>)

In [45]:
v.T, v

(array([ 1,  0, -1]), array([ 1,  0, -1]))

In [51]:
A.getcol(1).todense(), A.getrow(1).todense(), A.tocoo()

(matrix([[2],
         [0],
         [0]]),
 matrix([[0, 0, 3]], dtype=int64),
 <3x3 sparse matrix of type '<class 'numpy.int64'>'
 	with 5 stored elements in COOrdinate format>)

In [20]:
A = csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])
B = csr_matrix([[1], [0], [-1]])
A.dot(B).todense()

matrix([[ 1],
        [-3],
        [-1]], dtype=int64)

In [58]:
# sparse_vector_dot_oneliner(A,B)

In [ ]:
def sparse_vector_dot_oneliner(a: dict, b: dict):
    return sum(b[key]*value for key, value in a.items() if key in b)

In [36]:
def get_pointers(v: tuple):
    return {key: value for key, value in enumerate(v) if value}


def sparse_vector_dot(a: dict, b: dict):
    result = 0
    for key, value in a.items():
        if key in b:
            result += b[key] * value
    return result


a = (2, 4, 0, 0, 0, 6)
b = (0, 3, 4, 0, 0, 7)
a, b = get_pointers(a), get_pointers(b)
print(sparse_vector_dot(a, b))

54


In [33]:
a, b

({0: 2, 1: 4, 5: 6}, {1: 3, 2: 4, 5: 7})

In [34]:
a = (2, 4, 0, 0, 0, 6)
type(a)

tuple

In [37]:
sparse_vector_dot_oneliner(a,b)

54

In [39]:
a = (2, 4, 0, 0, 0, 6)
b = (0, 3, 4, 0, 0, 7)
for key, value in enumerate(a):
    print (key,value)

0 2
1 4
2 0
3 0
4 0
5 6


In [42]:
r = 0
for key, value in enumerate(a):
    r += value * b[key]
r

54

In [53]:
import scipy.sparse
import random
import itertools

def using_nonzero(x):
    rows,cols = x.nonzero()
    for row,col in zip(rows,cols):
        ((row,col), x[row,col])

def using_coo(x):
    cx = scipy.sparse.coo_matrix(x)    
    for i,j,v in zip(cx.row, cx.col, cx.data):
        (i,j,v)

def using_tocoo(x):
    cx = x.tocoo()    
    for i,j,v in zip(cx.row, cx.col, cx.data):
        (i,j,v)

def using_tocoo_izip(x):
    cx = x.tocoo()    
    for i,j,v in itertools.izip(cx.row, cx.col, cx.data):
        (i,j,v)

N=200
x = scipy.sparse.lil_matrix( (N,N) )
for _ in range(N):
    x[random.randint(0,N-1),random.randint(0,N-1)]=random.randint(1,100)

In [55]:
x

<200x200 sparse matrix of type '<class 'numpy.float64'>'
	with 200 stored elements in LInked List format>

In [56]:
using_tocoo(x)

In [57]:
cx = x.tocoo() 
for i,j,v in zip(cx.row, cx.col, cx.data):
    print (i,j,v)

3 30 6.0
3 167 26.0
6 29 23.0
6 65 32.0
7 129 46.0
10 23 61.0
12 72 94.0
12 90 89.0
12 196 6.0
13 128 71.0
15 54 22.0
15 131 60.0
17 108 21.0
17 195 87.0
18 85 83.0
18 88 65.0
19 57 68.0
19 80 64.0
20 41 76.0
20 179 76.0
22 105 85.0
24 138 88.0
24 141 59.0
25 8 73.0
26 139 83.0
26 175 72.0
29 132 9.0
30 33 46.0
31 176 44.0
32 137 30.0
33 57 65.0
37 42 22.0
37 71 82.0
38 5 64.0
39 77 100.0
40 18 66.0
42 73 50.0
42 121 38.0
44 134 44.0
45 61 11.0
50 90 5.0
51 149 13.0
54 19 27.0
54 198 4.0
55 46 18.0
55 119 93.0
59 94 47.0
60 117 9.0
60 137 32.0
61 40 24.0
61 72 83.0
62 188 60.0
64 74 70.0
64 177 10.0
65 65 43.0
65 154 84.0
66 134 77.0
68 88 40.0
68 106 58.0
68 157 66.0
69 107 45.0
70 152 38.0
71 4 80.0
73 144 69.0
74 46 63.0
75 13 55.0
75 35 100.0
75 190 62.0
78 5 7.0
78 18 42.0
80 25 35.0
81 6 44.0
81 11 49.0
81 104 30.0
81 133 32.0
83 2 12.0
84 58 47.0
85 47 47.0
85 115 50.0
85 130 39.0
85 155 18.0
86 11 63.0
86 178 59.0
87 93 78.0
88 20 7.0
88 32 49.0
88 101 23.0
88 198 48.0
89 44 43