In [3]:
X = [6,5,4]
Y = [3,2,1]
dotproduct=0
for i,j in zip(X,Y):
	dotproduct += i*j
print('Dot product is : ' , dotproduct)

Dot product is :  32


In [20]:
import numpy as np
from scipy.sparse import csr_matrix
A = csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])
B = csr_matrix([[1], [0], [-1]])
A.dot(B).todense()

matrix([[ 1],
        [-3],
        [-1]], dtype=int64)

In [23]:
print (B)

  (0, 0)	1
  (2, 0)	-1


In [37]:
# print (B[0,:])
# print (B[0])
# print (B[:,0])
print (B[2][0])

  (0, 0)	-1


In [48]:
cA = A.tocoo() 
cB = B.tocoo() 
sum = 0
for i,j,v in zip(cB.row, cB.col, cB.data):
    print (i,j,v)
    sum += v*B[i][j]
print (sum)   

0 0 1
2 0 -1
  (0, 0)	2


In [45]:
B.T.dot(B).todense()

matrix([[2]], dtype=int64)

In [71]:
cA = A.tocoo() 
cB = B.tocoo() 
sum = 0
for i,j,v in zip(cB.row, cB.col, cB.data):
    print (i,j,v)
#     print (v*A[i][j])
    sum += v*A[i][j]
print (sum)   


0 0 1
2 0 -1
  (0, 0)	-3
  (0, 1)	2
  (0, 2)	-5


In [74]:
(v*A[i][j]).todense()

matrix([[-4,  0, -5]])

In [64]:
sum.todense()

matrix([[-3,  2, -5]], dtype=int64)

In [65]:
(A.T*B).todense()

matrix([[-3],
        [ 2],
        [-5]], dtype=int64)

In [58]:
A.dot(B).todense()

matrix([[ 1],
        [-3],
        [-1]], dtype=int64)

In [7]:
cB.row

array([0, 2], dtype=int32)

In [8]:
cB.col

array([0, 0], dtype=int32)

In [9]:
cB.data

array([ 1, -1], dtype=int64)

In [11]:
B.todense()

matrix([[ 1],
        [ 0],
        [-1]], dtype=int64)

IndexError: invalid number of indices

In [16]:
np.zeros(shape=(B.shape[0],B.shape[1]))

array([[0.],
       [0.],
       [0.]])

In [12]:
help(np.dot)

Help on built-in function dot in module numpy.core.multiarray:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Se